# Generated by Django 5.2.6 on 2025-09-10 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz_app", "0002_alter_question_id_alter_quiz_id_alter_quizattempt_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blacklistedtoken",
            options={},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="quizattempt",
            options={"ordering": ["-created_at"]},
        ),
    ]
