# Docker Compose für Quizly (Vereinfacht)
services:
  web:
    image: python:3.11-slim
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    command: >
      bash -c "
        apt-get update && 
        apt-get install -y ffmpeg git wget && 
        pip install -r requirements.txt && 
        python manage.py migrate && 
        python manage.py runserver 0.0.0.0:8000
      "
    
volumes:
  media_volume:
  static_volume:
