services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - GEMINI_API_KEY=${GEMINI_API_KEY}

volumes:
  media_volume:
  static_volume:
