services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    env_file:
      - .env.docker
    environment:
      # Override specific variables for Docker
      - DATABASE_URL=postgres://quizly_user:quizly_password@db:5432/quizly
      - FORCE_SQLITE=false
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=quizly
      - POSTGRES_USER=quizly_user
      - POSTGRES_PASSWORD=quizly_password
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  media_volume:
  static_volume:
